### ISSUE TITLE
Question: Is there any org-roam feature that is *not* supported?

### ISSUE THREAD

**Issue by anthrolisp** [nobiot/md-roam#47]
Is there any org-roam feature that is **not** supported? Thanks in advance!

**Comment by nobiot** [comment]
This is a good question, and very difficult to answer exhaustively.
Let me try.

For the text written with markdown syntax, the ones listed in README work (or should work) because I use them with my markdown notes with Org-roam. The rest is in the gray zone; that is, I don't explicitly test them.

If you use Org syntax within markdown files, I am not really stopping them so they should work as long as Md-roam does not have an overlapping feature. But this is also in the gray area.

If you look beyond Org-roam at the "ecosystem"; e.g. `org-roam-server` and `org-roam-bibtex`, they are in the gray zone, too, and probably they don't work. I don't use them. For the graph, I could use Obsidian as a graph browser. For `bibtex`, I use Pandoc syntax, so I can use plain `helm-bibtex` with no extension; I don't use `org-ref` or `org-roam-bibtex`.

**Comment by nobiot** [comment]
Now that I have released V2, I'm closing this issue.
