### ISSUE TITLE
Question: Could you provide a basic tutorial on how to create an .md note and link to it?

### ISSUE THREAD

**Issue by Solcany** [nobiot/md-roam#49]
I installed this plugin on Doom Emacs as instructed and reloaded it.  

When i use 'Org Roam Capture' command(space+n+r+c) an .org file is created instead of .md file. When I try to create an .md note manually it doesn't get registered by org roam(space+n+r+r). I can't link to it using 'Org Roam insert'(space+n+r+i) from other .md notes because i can't see the newly crated one after using the command.

my config.el:
```
(use-package! md-roam 
  :config
  (setq md-roam-file-extension-single "md")
  (setq org-roam-title-sources '((mdtitle title mdheadline headline) (mdalias alias))))
```

my package.el:
```
(package! md-roam
  :recipe (:host gitlab
           :repo "nobiot/md-roam"))
```

**Comment by nobiot** [comment]
Do you have this too?

(setq org-roam-file-extensions '("org" "md"))

If you need to create an md file with org-roam-insert, try to put "md" as the first one in the list (instead of "org" as in this example).

The issue of "registering"...
Not sure what is exactly happening but I suspect two things:

- By default, Org-roam waits for you to be idle for 2 seconds before "registering" a newly created note in the DB

- Do you see "Md-roam active" in the echo when you start Org-roam? if not it Md-roam is not active

**Comment by Solcany** [comment]
thank you for your help, I was able to create an .md note as after setting the file extension with insert command.

However the newly created note wouldn't still get registered in my db, since i still don't see it in org roam buffer (space+n+r+r). I do see "Md-roam active" when i start org roam.

**Comment by nobiot** [comment]
@Solcany 

If you do not see "md-roam is active" in the echo when you run `org-roam-db-build-cache` (it's also automatically run when you activate `org-roam`), then it's almost certain that Md-roam is not loaded correctly.

Do you have this somewhere in your config file **before** `org-roam` is loaded?
```
(add-to-list 'load-path "~/path/to/md-roam-directory/") ;Modify with your own path
(require 'md-roam) ;this must be before org-roam
```
If this does not let you use Md-roam, I am not sure what else is stopping you from making it work.
Are you familiar enough with Emacs, and am I making sense to you?

My life does not let me commit to many things at the moment, and cannot write an easy tutorial. But I am considering of making Md-roam a bit easier. This has to be after Org-roam releases version 2, and will need to be after April/May based on my life at the moment.

**Comment by nobiot** [comment]
Alternatively, if `require` does not seem to work, you could also do this (before Org-roam):
```
(load-file "path/to/md-roam.el")
```

**Comment by nobiot** [comment]
Depending on how you write the links in your markdown files, you might need to adjust these variables:
```
  (setq md-roam-use-org-file-links nil)
  (setq md-roam-use-markdown-file-links t)
```
If you want to use the standard Markdown link syntax, the second one needs to be turned on (default nil) -- this was because these are newly added variables, and wanted to keep old behaviours consistent. Maybe a time for review, if this is the problem you have experienced. 

Let me know...

**Comment by nobiot** [comment]
With V2 and its README, I'm hoping the basic operation is clearer. Closing this issue.
