### ISSUE TITLE
[Feature] Support of org-mode TODOs within md files

### ISSUE THREAD

**Issue by wakatara** [nobiot/md-roam#71]
Quite honestly, having TODOs a la org-mode supported within the md files would make this incredible as you could also use it within your org-agenda etc (as well as being abel to attach notes via C-c z etc) to them. 

Is there any major impediment for that working with the markdown files currently? 

(I've always admired logseq for making org-mode todos available within markdown-ish documents.)

**Comment by nobiot** [comment]
Sorry I do not think it should be part of md-roam. It is just an integration piece between markdown files and org-roam-db. It does not touch the syntax or any feature of markdown itself. 

I personally rely  on markdown-mode for markdown files.

**Comment by wakatara** [comment]
Fair enough. I was thinking of it more in terms of a seamless integration with the rest of org-mode and org-roam. 

Tbh, if I could, I'd just use markdown and md-roam for everything and the use of org-mode TODOs in them would just make *everything* better. =]  Org-mode's primary advantage from my perspective is its superlative task management driven by the way they handle TODOs (and org-agenda and friends... ).

I'm assuming if I wanted to write in support for this myself I would need to fork markdown mode then? But otherwise, roam-md would just work as advertised?

**Comment by nobiot** [comment]
> But otherwise, roam-md would just work as advertised?

It should. Assuming you did something like this:
```markdown
# TODO task 1
# TODO task 2
```
For markdown, TODO is just a string and the whole "TODO task 1" is, syntactically the headline. So I don't see why this influences markdown or md-roam.

> I'm assuming if I wanted to write in support for this myself I would need to fork markdown mode then?

You would not even need to fork markdown-mode. But before considering coding, why not simply turn on Org-mode on a markdown file and have something like this:

```org
* TODO task 1
- note 1
- note 2
* TODO task 2

# Markdown heading H1
```

The file is a valid Org file (with `.md` extension) -- the meaning of "#" is a comment in Org syntax but it should not present any issue. Maybe you need to configure Org-agenda to take `.md` files as a valid `.org` files, but otherwise, you might not need to code anything (?)

When you want to use some markdown specific capability, you would switch on `markdown-mode`. The "*" and "-" parts would then become normal bullet points in Markdown. Again that would be syntactically valid, too.

Just a thought.

**Comment by wakatara** [comment]
Hmmm... interesting, but then I don't get the headings folding on markdown files and link syntax. Lemme close this as I tried something different with roam-md but ran into troubles. Think it's a big, but not sure.
